### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by borismattijssen** [borismattijssen/information-retrieval#1]
## To research:
- [ ] Check if source code is available from original paper
- [ ] Woosh IR Toolkit
- [ ] APONE
- [ ] ANOVA

## To ask:
- [ ] How much time do we have in class for the experiment?
